# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
    ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
    networks."50-eth1" = {
      matchConfig.Name = "eth1";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  time.timeZone = "Europe/Budapest";

  networking.firewall = {
    enable = true;
    trustedInterfaces = [ "tailscale0" ];
    allowedUDPPorts = [ 
      config.services.tailscale.port 
    ];
  };

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    man-pages
    man-pages-posix
    tailscale 
    firefox
    vscode
    fish
    zellij
    wget
    vim
    btop
    htop
    thefuck
    dnsutils
    mc
    git
    rclone
  ];

  fonts.packages = with pkgs; [
    font-awesome
    powerline-fonts
    powerline-symbols
    (nerdfonts.override { fonts = [ "NerdFontsSymbolsOnly" ]; })
  ];

  programs = {
    fish.enable = true;
    gnupg.agent = {
      enable = true;
      enableSSHSupport = true;
    };
  }; 

  #users.users.root.hashedPassword = "!";
  users.users.casper = {
    isNormalUser = true;
    description = "Zoltán Bálint";
    extraGroups = [
      "wheel" # Enable ‘sudo’ for the user.
      "networkmanager" # Access to networkmanager
    ];
    shell = pkgs.fish;
  };

  console.keyMap = "hu";

  services = {
    tailscale.enable = true;
    openssh.enable = false;
    
    xserver = {
      enable = true;
      xkb.layout="hu";
      xkb.variant = "";
      desktopManager.xfce.enable = true;
      displayManager.lightdm.enable = true;
      displayManager.sessionCommands = "xkbcomp /home/casper/.keyboard_layout_hax/layout.xkb $DISPLAY";
    };

    xrdp = {
      enable = true;
      defaultWindowManager = "xfce4-session";
      # does not needed because of tailscale
      # openFirewall = true;
    };

    displayManager = {
      defaultSession = "xfce";
      autoLogin.enable = false;
      autoLogin.user = "casper";
    };
  };

  system.stateVersion = "24.05"; # Did you read the comment?
}
